### ISSUE TITLE
How to download ?

### ISSUE THREAD

**Issue by doug-scott** [DenisShelema/MKS-TFT3.5-light-and-dark-themes#1]
I am not a developer, have no experience with github.  I am just a simple user.  Your screen and icons are very attractive.  I don't know if you have both dark and light versions available for download, but I have l not been able to find it.  How can I download these screens?

**Comment by DenisShelema** [comment]
[MKS-TFT3.5 user manual](https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT%203.5%20V1.0DataSheet.pdf)
